<a href="https://colab.research.google.com/github/Dexless/Colab-Repo/blob/main/126_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sqlalchemy import create_engine, text
from google.colab import userdata
import kagglehub
import psycopg2
from psycopg2.extras import execute_values
import pandas as pd
import os

In [ ]:
try:
  preview_user = False
  NEON_CON_2 = userdata.get("NEON_ADMIN_PROJECT_2")
  engine = create_engine(NEON_CON_2)
  connection = psycopg2.connect(NEON_CON_2)
  cursor = connection.cursor()
except:
  preview_user = True
  NEON_CON_2 = "postgresql://readonly_user:readonly_user@ep-flat-recipe-akzdkq5t-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"# Read Only User
  engine = create_engine(NEON_CON_2)
  connection = psycopg2.connect(NEON_CON_2)
  cursor = connection.cursor()

print(preview_user)
connection.autocommit = True

False

In [ ]:
# Kaggle Import of the dataset
# Sometimes Have to run it twice
if(not preview_user):
  ASTEROID_PATH = "/kaggle/input/asteroid-dataset"
  NEOWS_PATH = "/kaggle/input/neows-hazardous-asteroid-dataset/NeoWS"

  if(not (os.path.exists(ASTEROID_PATH) and os.path.exists(NEOWS_PATH))):
    a_ds = kagglehub.dataset_download("sakhawat18/asteroid-dataset")
    neo_ds = kagglehub.dataset_download("alvinb/neows-hazardous-asteroid-dataset")

In [ ]:
# @title
if(not preview_user):
  asteroid_table = '''
  CREATE TABLE IF NOT EXISTS asteroid_reduced(
    id TEXT,
    spkid INT PRIMARY KEY,
    full_name TEXT,
    pdes TEXT,
    neo BOOL,
    pha BOOL,
    H FLOAT,
    orbit_id TEXT,
    epoch FLOAT,
    epoch_mjd INT,
    epoch_cal FLOAT,
    equinox TEXT,
    e DOUBLE PRECISION,
    a DOUBLE PRECISION,
    q DOUBLE PRECISION,
    i DOUBLE PRECISION,
    om DOUBLE PRECISION,
    w DOUBLE PRECISION,
    ma DOUBLE PRECISION,
    ad DOUBLE PRECISION,
    n DOUBLE PRECISION,
    tp DOUBLE PRECISION,
    tp_cal DOUBLE PRECISION,
    per DOUBLE PRECISION,
    per_y DOUBLE PRECISION,
    moid DOUBLE PRECISION,
    moid_ld DOUBLE PRECISION,
    sigma_e DOUBLE PRECISION,
    sigma_a DOUBLE PRECISION,
    sigma_q DOUBLE PRECISION,
    sigma_i DOUBLE PRECISION,
    sigma_om DOUBLE PRECISION,
    sigma_w DOUBLE PRECISION,
    sigma_ma DOUBLE PRECISION,
    sigma_ad DOUBLE PRECISION,
    sigma_n DOUBLE PRECISION,
    sigma_tp DOUBLE PRECISION,
    sigma_per DOUBLE PRECISION,
    orbit_class TEXT,
    rms DOUBLE PRECISION);'''

  neows_table = '''
  CREATE TABLE IF NOT EXISTS close_approach_reduced(
    approach_id INT PRIMARY KEY,
    a_date DATE,
    neo_reference_id INT,
    absolute_magnitude DOUBLE PRECISION,
    estimated_diameter_km_min DOUBLE PRECISION,
		estimated_diameter_km_max DOUBLE PRECISION,
    close_approach_date DATE,
    epoch_date_close_approach BIGINT,
    relative_velocity_km_per_hr DOUBLE PRECISION,
    miss_dist_a DOUBLE PRECISION,
    miss_dist_l DOUBLE PRECISION,
    miss_dist_km DOUBLE PRECISION,
    miss_dist_m DOUBLE PRECISION,
    orbiting_body TEXT,
    orbit_id INT,
    orbit_determination_date TIMESTAMP,
    orbit_uncertainty INT,
    minimum_orbit_intersection DOUBLE PRECISION,
    jupiter_tisserand_invariant DOUBLE PRECISION,
    epoch_osculation DOUBLE PRECISION,
    eccentricity DOUBLE PRECISION,
    semi_major_axis DOUBLE PRECISION,
    inclination DOUBLE PRECISION,
    asc_node_longitude DOUBLE PRECISION,
    orbital_period DOUBLE PRECISION,
    perihelion_distance DOUBLE PRECISION,
    perihelion_arg DOUBLE PRECISION,
    aphelion_dist DOUBLE PRECISION,
    perihelion_time DOUBLE PRECISION,
    mean_anomaly DOUBLE PRECISION,
    mean_motion DOUBLE PRECISION,
    equinox TEXT,
    hazardous BOOL);'''

try:
  cursor.execute(asteroid_table)
  cursor.execute(neows_table)
  print("tables successfully created or was already there!")
except:
  print("Table failed to create, SQL error...")

tables successfully created or was already there!

## 1) Reduce the size of the original datasets and transfer to other database

In [ ]:
if(not preview_user):
  DS_1 =  pd.read_csv(NEOWS_PATH + "/data_1900_1950_updated_December.csv", low_memory=False)
  DS_2 =  pd.read_csv(NEOWS_PATH + "/data_1950_2000.csv", low_memory=False)
  DS_3 =  pd.read_csv(NEOWS_PATH + "/data_1953_2000.csv", low_memory=False)
  DS_4 =  pd.read_csv(NEOWS_PATH + "/data_2002_2022.csv", low_memory=False)
  DS_5 =  pd.read_csv(NEOWS_PATH + "/data_2022_present.csv", low_memory=False)
  asteroid_df = pd.read_csv(ASTEROID_PATH + "/dataset.csv", low_memory=False)
  asteroid_schema_df = pd.read_sql("SELECT * FROM asteroid_reduced LIMIT 0;",con=engine)
  close_schema_df = pd.read_sql("SELECT * FROM close_approach_reduced LIMIT 0;",con=engine)

  DS_LIST = [DS_1, DS_2, DS_3, DS_4, DS_5]
  close_approach_df = pd.concat(DS_LIST, ignore_index=0)

  asteroid_df = asteroid_df.drop(axis = 1, columns=["name", "prefix", "diameter", "albedo", "diameter_sigma"]) # Nothing in these cols
  close_approach_df = close_approach_df.drop(axis = 1, columns=["Unnamed: 0", "Name", "Est Dia in M(min)", "Est Dia in M(max)", "Est Dia in Miles(min)", "Est Dia in Miles(max)",
  "Est Dia in Feet(min)", "Est Dia in Feet(max)", "Relative Velocity km per sec", "Miles per hour"]) # Redundant in these cols
  close_approach_df.insert(0, "approach_id", range(1, len(close_approach_df) + 1))

  asteroid_df.columns = asteroid_schema_df.columns
  close_approach_df.columns = close_schema_df.columns

In [ ]:
# SELECT * FROM asteroid a WHERE EXISTS (SELECT 1 FROM close_approach c WHERE c.neo_reference_id = a.spkid);
# SELECT * FROM close_approach c WHERE EXISTS (SELECT 1 FROM asteroid a WHERE a.spkid = c.neo_reference_id);
if(not preview_user):
  asteroid_ids = asteroid_df["spkid"]
  close_ids = close_approach_df["neo_reference_id"]

  asteroid_df = asteroid_df[asteroid_df["spkid"].isin(close_ids)].copy()
  close_approach_df = close_approach_df[close_approach_df["neo_reference_id"].isin(asteroid_ids)].copy()

In [ ]:
#Transfer
if(not preview_user):
  asteroid_df.to_sql(name='asteroid_reduced', con=engine, if_exists='append', index=False, method='multi',chunksize=1000)
  close_approach_df.to_sql(name='close_approach_reduced', con=engine, if_exists='append', index=False, method='multi',chunksize=1000)

In [ ]:
# Verify Inserts
if(not preview_user):
  query = "SELECT count(*) FROM asteroid_reduced;"
  cursor.execute(query)
  asteroid_size = cursor.fetchone()

  query = "SELECT count(*) FROM close_approach_reduced;"
  cursor.execute(query)
  close_approach_size = cursor.fetchone()

  print(f"Were all asteroid_reduced enetered from the df?: {asteroid_size[0] == len(asteroid_df)}")
  print(f"Were all close_approach_reduced enetered from the df?: {close_approach_size[0] == len(close_approach_df)}")

Were all asteroid_reduced enetered from the df?: True
Were all close_approach_reduced enetered from the df?: True

## 2) Drop / Move Attributes that violate 3NF rules

In [ ]:
if not preview_user:
    ASTEROID_DELETE_LIST = [
        "name", "prefix", "diameter", "albedo", "diameter_sigma", "neo", "pha", "id", "pdes", "condition_code",
        "epoch", "epoch_mjd", "epoch_cal", "equinox", "tp", "tp_cal", "per_y", "moid_ld", "moid_jup",
        "sigma_e", "sigma_a", "sigma_q", "sigma_i", "sigma_om", "sigma_w", "sigma_ma", "sigma_ad", "sigma_n",
        "sigma_tp", "sigma_per", "rms", "w", "om", "ma", "n", "ad"
    ]

    CLOSE_APPROACH_DELETE_LIST = [
        "absolute_magnitude", "epoch_date_close_approach",
        "miss_dist_a", "miss_dist_l", "miss_dist_m", "orbit_id", "orbit_determination_date", "orbit_uncertainty",
        "minimum_orbit_intersection", "jupiter_tisserand_invariant", "epoch_osculation", "eccentricity",
        "semi_major_axis", "inclination", "asc_node_longitude", "orbital_period", "perihelion_distance",
        "perihelion_arg", "aphelion_dist", "perihelion_time", "mean_anomaly", "mean_motion", "equinox"
    ]

    for col in ASTEROID_DELETE_LIST:
        query = f'ALTER TABLE asteroid_reduced DROP COLUMN IF EXISTS "{col}";'
        cursor.execute(query)

    for col in CLOSE_APPROACH_DELETE_LIST:
        query = f'ALTER TABLE close_approach_reduced DROP COLUMN IF EXISTS "{col}";'
        cursor.execute(query)

    connection.commit()

In [ ]:
if(not preview_user):
  query = '''ALTER TABLE asteroid_reduced
  ADD COLUMN
    estimated_diameter_km_min DOUBLE PRECISION,
  ADD COLUMN
    estimated_diameter_km_max DOUBLE PRECISION,
  ADD COLUMN
    hazardous BOOL;'''
  cursor.execute(query)

In [ ]:
if(not preview_user):
  query = '''UPDATE asteroid_reduced a SET
  hazardous = c.hazardous,
  estimated_diameter_km_min = c.estimated_diameter_km_min,
  estimated_diameter_km_max = c.estimated_diameter_km_max
  FROM close_approach_reduced c WHERE a.spkid = c.neo_reference_id;'''
  cursor.execute(query)

In [ ]:
if(not preview_user):
  query = '''ALTER TABLE close_approach_reduced
  DROP COLUMN
    estimated_diameter_km_min,
  DROP COLUMN
    estimated_diameter_km_max,
  DROP COLUMN
    hazardous
  '''
  cursor.execute(query)

## 3) Which asteroids have the most recorded close approaches?

In [ ]:
query = '''SELECT
    a.spkid,
    a.full_name,
    COUNT(c.approach_id) AS close_approach_count
FROM asteroid_reduced AS a
JOIN close_approach_reduced AS c
ON a.spkid = c.neo_reference_id
GROUP BY
    a.spkid,
    a.full_name
ORDER BY close_approach_count DESC limit 5;'''
df = pd.read_sql(con = engine, sql = query)
df.head()

     spkid                      full_name  close_approach_count
0  2277810             277810 (2006 FV35)                   251
1  2469219  469219 Kamo`oalewa (2016 HO3)                   217
2  3678630                   (2014 OL339)                   183
3  3771633                     (2017 FZ2)                   173
4  2164207              164207 (2004 GU9)                   165

## 4) Which asteroid have come closest to Earth based on minimum miss_dist_km?

In [ ]:
query = '''SELECT
    a.spkid,
    a.full_name,
    MIN(c.miss_dist_km) AS closest_recorded_miss
FROM asteroid_reduced AS a
JOIN close_approach_reduced AS c
ON a.spkid = c.neo_reference_id
GROUP BY
    a.spkid,
    a.full_name
ORDER BY closest_recorded_miss ASC
LIMIT 5;'''
df = pd.read_sql(con = engine, sql = query)
df.head()

      spkid            full_name  closest_recorded_miss
0   3556206           (2011 CQ1)           11851.666854
1   3892165          (2019 UN13)           12613.434168
2   3430497          (2008 TS26)           12638.162696
3   3249978         (2004 FU162)           12913.138541
4  54000953           (2020 CD3)           13104.324618

## 5) What are the top 5 closest approaches to Earth in the dataset?

In [ ]:
query = '''SELECT
    a.spkid,
    a.full_name,
    c.miss_dist_km,
    c.orbiting_body
  FROM asteroid_reduced as a
  JOIN close_approach_reduced AS c
  ON a.spkid = c.neo_reference_id
  ORDER BY miss_dist_km ASC LIMIT 5'''
df = pd.read_sql(con = engine, sql = query)
df.head()

      spkid            full_name  miss_dist_km orbiting_body
0   3556206           (2011 CQ1)  11851.666854         Earth
1   3892165          (2019 UN13)  12613.434168         Earth
2   3430497          (2008 TS26)  12638.162696         Earth
3   3249978         (2004 FU162)  12913.138541         Earth
4  54000953           (2020 CD3)  13104.324618         Earth

## 6) Which orbit classes have the greatest number of asteroids?

In [ ]:
query = '''SELECT
    orbit_class,
    COUNT(*) AS asteroid_count
FROM asteroid_reduced
GROUP BY orbit_class
ORDER BY asteroid_count DESC
LIMIT 5;'''
df = pd.read_sql(con = engine, sql = query)
df.head()

  orbit_class  asteroid_count
0         APO           12547
1         AMO            8190
2         ATE            1724
3         MCA              23
4         IEO              22

## 7) Which orbit classes have the smallest average MOID (Minimum Orbit Intersection Distance)

In [ ]:
query = '''SELECT
    orbit_class,
    COUNT(moid) AS asteroid_count,
    AVG(moid) AS average_moid
  FROM asteroid_reduced
  GROUP BY
    orbit_class
  ORDER BY average_moid ASC LIMIT 5'''
df = pd.read_sql(con = engine, sql = query)
df.head()

  orbit_class  asteroid_count  average_moid
0         ATE            1724      0.044097
1         APO           12547      0.049672
2         IEO              22      0.118305
3         AMO            8190      0.162406
4         MCA              23      0.355105

## 8) How many close approaches occur in each year?

In [ ]:
query = '''SELECT
    DATE_TRUNC('year', close_approach_date) AS year,
    COUNT(*) AS total_approaches
  FROM close_approach_reduced
  GROUP BY
    year
  ORDER BY total_approaches DESC LIMIT 5'''
df = pd.read_sql(con = engine, sql = query)
df.head()

                       year  total_approaches
0 2019-01-01 00:00:00+00:00              5645
1 2017-01-01 00:00:00+00:00              5263
2 2018-01-01 00:00:00+00:00              5174
3 2016-01-01 00:00:00+00:00              5004
4 2015-01-01 00:00:00+00:00              4630

## 9) Which orbit classes have the highest average close-approach velocity?

In [ ]:
query = '''SELECT
    a.orbit_class,
    AVG(c.relative_velocity_km_per_hr) AS velocity
  FROM asteroid_reduced as a
  JOIN close_approach_reduced AS c
  ON a.spkid = c.neo_reference_id
  GROUP BY
    a.orbit_class
  ORDER BY velocity DESC LIMIT 5'''
df = pd.read_sql(con = engine, sql = query)
df.head()

  orbit_class      velocity
0         IEO  58840.614322
1         APO  57244.661088
2         ATE  53167.999576
3         AMO  36289.173305
4         MBA  26043.855778

## 10) Which orbit classes have the largest average estimated asteroid diameter?

In [ ]:
query = '''SELECT
    orbit_class,
    AVG((estimated_diameter_km_min + estimated_diameter_km_max) / 2) AS avg_diameter
  FROM asteroid_reduced
  GROUP BY
    orbit_class
  ORDER BY avg_diameter DESC LIMIT 5'''
df = pd.read_sql(con = engine, sql = query)
df.head()

  orbit_class  avg_diameter
0         IEO      0.910355
1         MBA      0.656966
2         MCA      0.601766
3         AMO      0.345292
4         APO      0.247662

## 11) Among hazardous asteroids, which ones have the smallest miss distances?

In [ ]:
query = '''SELECT
    a.spkid,
    a.full_name,
    c.miss_dist_km,
    a.hazardous
  FROM asteroid_reduced as a
  JOIN close_approach_reduced AS c
  ON a.spkid = c.neo_reference_id
  WHERE a.hazardous IS true
  ORDER BY c.miss_dist_km ASC LIMIT 5'''
df = pd.read_sql(con = engine, sql = query)
df.head()

     spkid           full_name   miss_dist_km  hazardous
0  3838139          (2019 CD2)   75303.304219       True
1  3789399         (2017 VW13)  143272.707499       True
2  2152680   152680 (1998 KJ9)  233048.154541       True
3  3125003          (2002 JE9)  267511.180410       True
4  3610024         (2012 TY52)  314288.235270       True

## 12) Do hazardous asteroids have a higher average relative velocity than non-hazardous ones?

In [ ]:
query = '''SELECT
    a.hazardous,
    AVG(c.relative_velocity_km_per_hr) AS velocity
  FROM asteroid_reduced as a
  JOIN close_approach_reduced AS c
  ON a.spkid = c.neo_reference_id
  GROUP BY
    a.hazardous
  ORDER BY velocity DESC'''
df = pd.read_sql(con = engine, sql = query)
df.head()

   hazardous      velocity
0       True  63334.820866
1      False  50083.842257

## 13) Which hazardous close approaches are closer than the average miss distance?

In [ ]:
query = '''SELECT
  a.full_name,
  c.close_approach_date,
  c.miss_dist_km,
  a.hazardous
FROM close_approach_reduced AS c
JOIN asteroid_reduced AS a
  ON a.spkid = c.neo_reference_id
WHERE a.hazardous IS TRUE
AND c.miss_dist_km <
  (SELECT AVG(miss_dist_km)
   FROM close_approach_reduced
   WHERE miss_dist_km IS NOT NULL)
ORDER BY c.miss_dist_km ASC
LIMIT 5;
'''
df = pd.read_sql(con=engine, sql=query)
df.head()

            full_name close_approach_date   miss_dist_km  hazardous
0          (2019 CD2)          1957-02-01   75303.304219       True
1         (2017 VW13)          2001-11-08  143272.707499       True
2   152680 (1998 KJ9)          1914-12-31  233048.154541       True
3          (2002 JE9)          1971-04-11  267511.180410       True
4         (2012 TY52)          1982-11-04  314288.235270       True

## 14) Which orbit classes have an average MOID lower than the overall average MOID?

In [ ]:
query = '''SELECT
  orbit_class,
  COUNT(moid) AS asteroid_count,
  AVG(moid) AS average_moid
FROM asteroid_reduced
WHERE moid IS NOT NULL
GROUP BY orbit_class
HAVING AVG(moid) <
  (SELECT AVG(moid)
  FROM asteroid_reduced
  WHERE moid IS NOT NULL)
ORDER BY average_moid ASC;
'''
df = pd.read_sql(con=engine, sql=query)
df.head()

  orbit_class  asteroid_count  average_moid
0         ATE            1724      0.044097
1         APO           12547      0.049672

## 15) How can we create a reusable combined table of asteroid details and close-approach events for later analysis?

In [ ]:
if(not preview_user):
  query = '''
  CREATE OR REPLACE VIEW asteroid_close_approach_view AS
  SELECT
      a.spkid,
      a.full_name,
      a.h AS absolute_magnitude,
      a.orbit_class,
      a.moid,
      a.estimated_diameter_km_min,
      a.estimated_diameter_km_max,
      c.approach_id,
      c.close_approach_date,
      c.relative_velocity_km_per_hr,
      c.miss_dist_km,
      c.orbiting_body,
      a.hazardous
  FROM asteroid_reduced AS a
  JOIN close_approach_reduced AS c
      ON a.spkid = c.neo_reference_id;
  '''
  cursor.execute(query)
  connection.commit()

In [ ]:
query = '''SELECT
  *
FROM asteroid_close_approach_view
LIMIT 5;
'''
df = pd.read_sql(con=engine, sql=query)
df.head()

,spkid,full_name,absolute_magnitude,orbit_class,moid,estimated_diameter_km_min,estimated_diameter_km_max,approach_id,close_approach_date,relative_velocity_km_per_hr,miss_dist_km,orbiting_body,hazardous
0,2068347,68347 (2001 KB67),19.8,ATE,0.014172,0.275775,0.616652,1,1900-01-05,57252.476842,5.991763e+07,Earth,True
1,2086450,86450 (2000 CK33),18.2,ATE,0.125339,0.540200,1.207925,2,1900-01-05,60504.724263,2.246854e+07,Earth,False
2,3102762,(2002 AA29),24.1,ATE,0.011840,0.040230,0.089958,3,1900-01-05,47727.643143,6.152521e+07,Earth,False
3,2293054,293054 (2006 WP127),18.4,APO,0.091950,0.535248,1.196851,6,1900-01-06,90618.495158,1.615271e+07,Earth,False
4,3548660,(2010 TP54),21.7,APO,0.040831,0.120936,0.270421,7,1900-01-06,58038.843010,3.389918e+07,Earth,True